#! /usr/bin/env python
import os
import shutil

from meta.data import NCBI as ncbi

ncbi.setup_assembly_info('genbank')
ncbi.setup_assembly_info('refseq')

shutil.move('NCBI.db', './meta/data/NCBI.db')